services:
  cleanflow-db:
    image: postgis/postgis:16-3.4
    container_name: cleanflow-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cleanflow-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
