info:
  name: configure actual container
  type: http
  seq: 21

http:
  method: POST
  url: "{{actual_url}}/actual-container"
  body:
    type: json
    data: |-
      {
        "container_id": 3
      }
  auth:
    type: bearer
    token: eyJhbGciOiJIUzI1NiJ9.eyJsYXN0X25hbWUiOiJTYW4gSXNpZHJvIiwiZmlyc3RfbmFtZSI6IkFkbWluIiwiaWQiOjEsInJvbGUiOiJBRE1JTiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiZXhwIjoxNzgwNDM0OTA0fQ.vFe1_puz_OYHBKHHYweTiTNZSeuQc5M8GAwyCi9LBb0

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
