info:
  name: configure actual container
  type: http
  seq: 21

http:
  method: POST
  url: "{{actual_url}}/actual-container"
  body:
    type: json
    data: |-
      {
        "container_id": 5
      }
  auth:
    type: bearer
    token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImxhc3RfbmFtZSI6IkFkbWluIiwiZmlyc3RfbmFtZSI6IlNhbiBJc2lkcm8iLCJpZCI6MSwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzgxNDIwODM2fQ.eB19O8nEfOGgpf1wV4bH1_kli9_O3MtnCjxSdyJEZ_Y

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
